#!/bin/bash
#
# Derived from initscripts-macvlan
# Copyright (C) 2014 Lars Kellogg-Stedman
#
# Adopted for veth by Oleksandr Natalenko <o.natalenko@lanet.ua>
# Copyright (C) 2015 Lanet Network
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /etc/init.d/functions

cd /etc/sysconfig/network-scripts
. ./network-functions

[ -f ../network ] && . ../network

CONFIG=${1}

need_config ${CONFIG}

source_config

OTHERSCRIPT="/etc/sysconfig/network-scripts/ifup-${REAL_DEVICETYPE}"

if [ ! -x ${OTHERSCRIPT} ]; then
	OTHERSCRIPT="/etc/sysconfig/network-scripts/ifup-eth"
fi

ip link add \
	name ${DEVICE} \
	type veth \
	peer name ${DEVICE}-bp

ip link set \
	dev ${DEVICE} \
	address ${VETH_MAC}

brctl addif \
	${VETH_PARENT} \
	${DEVICE}-bp

ip link set \
	dev ${DEVICE}-bp up

${OTHERSCRIPT} ${CONFIG}

